// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6dQPmcMKAP7gHYtiTquSma_msosfqk1k',
    appId: '1:123423309183:web:c99c6efba6ffbe8229ae4a',
    messagingSenderId: '123423309183',
    projectId: 'phlipkart-689dc',
    authDomain: 'phlipkart-689dc.firebaseapp.com',
    storageBucket: 'phlipkart-689dc.appspot.com',
    measurementId: 'G-GZJJLZTLXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4MlRNpsSIeKxvlQ3uJIZuoIYiVXicdE0',
    appId: '1:123423309183:android:fa91a9fad48f483f29ae4a',
    messagingSenderId: '123423309183',
    projectId: 'phlipkart-689dc',
    storageBucket: 'phlipkart-689dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU6p0BXjfYNAmArfNY1tzT9qC9CkcNPKk',
    appId: '1:123423309183:ios:9a1e21bfe1e9061729ae4a',
    messagingSenderId: '123423309183',
    projectId: 'phlipkart-689dc',
    storageBucket: 'phlipkart-689dc.appspot.com',
    iosBundleId: 'com.example.flipcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU6p0BXjfYNAmArfNY1tzT9qC9CkcNPKk',
    appId: '1:123423309183:ios:9a1e21bfe1e9061729ae4a',
    messagingSenderId: '123423309183',
    projectId: 'phlipkart-689dc',
    storageBucket: 'phlipkart-689dc.appspot.com',
    iosBundleId: 'com.example.flipcart',
  );
}
